sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tQdtuYcynhbkcoyNq6z
    access-key-secret: ftpuWF9vkXpqgRgboFQOeFsztioavW
    bucket-name: web-zyq1415
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxd2818c722748b536
    secret: 0a3d9aadcc88cf73b8d30a04bc82a9bc
    mchid: //商户号
    mchSerialNo: //商户API证书的证书序列号
    privateKeyFilePath: //商户私钥文件
    apiV3Key: //证书解密的密钥
    weChatPayCertFilePath: //平台证书
    notifyUrl: //支付成功的回调地址
    refundNotifyUrl: //退款成功的回调地址